# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Basys3_Master.xdc

# Block Designs: bd/system3/system3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system3 || ORIG_REF_NAME==system3} -quiet] -quiet

# IP: bd/system3/ip/system3_clkDivide_0_0/system3_clkDivide_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system3_clkDivide_0_0 || ORIG_REF_NAME==system3_clkDivide_0_0} -quiet] -quiet

# IP: bd/system3/ip/system3_segmentDriver_0_0/system3_segmentDriver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system3_segmentDriver_0_0 || ORIG_REF_NAME==system3_segmentDriver_0_0} -quiet] -quiet

# IP: bd/system3/ip/system3_calculator_0_0/system3_calculator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system3_calculator_0_0 || ORIG_REF_NAME==system3_calculator_0_0} -quiet] -quiet

# IP: bd/system3/ip/system3_xlconstant_0_0/system3_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system3_xlconstant_0_0 || ORIG_REF_NAME==system3_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/OarChula/Documents/GitHub/2110363-HWSynLab/lab04/lab04.gen/sources_1/bd/system3/system3_ooc.xdc
